export default interface ICreateUserDTO{
    name:string, 
    surname:string,
    email:string,
    birthDate:Date,
    password:string,
    cpf:string,
    cnpj:string,
    street:string,
    houseNumber:number,
    district:string, 
    complement:string,
    reference:string,
    phoneNumber:string,
    phoneNumber2:string,
    idCity:number,
    avatar:string,
    gender:string
}